### ISSUE TITLE
请问跨平台吗

### ISSUE THREAD

**Issue by gitnoobbbb** [likun7981/hlink#10]
windows好像不是很支持,报错了

**Comment by likun7981** [comment]
没有验证过windows \尴尬

**Comment by likun7981** [comment]
可以先提供下报错截图么

**Comment by gitnoobbbb** [comment]
> 可以先提供下报错截图么

[prtsc](https://i.loli.net/2020/12/14/ajC5ToAwRduUZBS.png)
上边是部分截图外链,下边是全部错误代码,就链接了4个文件,都没成,文件夹大部分一级,最多就两级...
`Error: Command failed with exit code 1 (Unknown system error -1): ls -i G:\movies\Hotel.Transylvania.2.2015.UHD.MasterRip.2160p.x265.10bit.SDR.TrurHD.5.1.mUHD-FRDS.mkv
    at makeError (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\node_modules\execa\lib\error.js:59:11)
    at Function.module.exports.sync (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\node_modules\execa\index.js:187:17)
    at getLinkPath (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\utils.js:29:21)
    at checkLinkExist (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\utils.js:36:17)
    at C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\index.js:191:17
    at Array.forEach (<anonymous>)
    at start (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\index.js:157:22)
    at hardLink (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\index.js:217:3)
    at Object.<anonymous> (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\cli.js:63:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  command: 'ls -i G:\\movies\\Hotel.Transylvania.2.2015.UHD.MasterRip.2160p.x265.10bit.SDR.TrurHD.5.1.mUHD-FRDS.mkv',
  exitCode: 1,
  exitCodeName: 'Unknown system error -1',
  stdout: '',
  stderr: "'ls' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\r\n���������ļ���",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined
}
Error: Command failed with exit code 1 (Unknown system error -1): ls -i G:\movies\Leap.2020.1080p.WEB-DL.x264.AAC-TJUPT.mp4
    at makeError (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\node_modules\execa\lib\error.js:59:11)
    at Function.module.exports.sync (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\node_modules\execa\index.js:187:17)
    at getLinkPath (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\utils.js:29:21)
    at checkLinkExist (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\utils.js:36:17)
    at C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\index.js:191:17
    at Array.forEach (<anonymous>)
    at start (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\index.js:157:22)
    at hardLink (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\index.js:217:3)
    at Object.<anonymous> (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\cli.js:63:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  command: 'ls -i G:\\movies\\Leap.2020.1080p.WEB-DL.x264.AAC-TJUPT.mp4',
  exitCode: 1,
  exitCodeName: 'Unknown system error -1',
  stdout: '',
  stderr: "'ls' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\r\n���������ļ���",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined
}
Error: Command failed with exit code 1 (Unknown system error -1): ls -i G:\movies\Tenet.2020.4K.WEB-DL.H265.2Audios-TJUPT.mp4
    at makeError (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\node_modules\execa\lib\error.js:59:11)
    at Function.module.exports.sync (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\node_modules\execa\index.js:187:17)
    at getLinkPath (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\utils.js:29:21)
    at checkLinkExist (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\utils.js:36:17)
    at C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\index.js:191:17
    at Array.forEach (<anonymous>)
    at start (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\index.js:157:22)
    at hardLink (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\index.js:217:3)
    at Object.<anonymous> (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\cli.js:63:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  command: 'ls -i G:\\movies\\Tenet.2020.4K.WEB-DL.H265.2Audios-TJUPT.mp4',
  exitCode: 1,
  exitCodeName: 'Unknown system error -1',
  stdout: '',
  stderr: "'ls' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\r\n���������ļ���",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined
}
Error: Command failed with exit code 1 (Unknown system error -1): ls -i G:\movies\阿波罗11号.Apollo.11.2019.BluRay.2160p.x265.10bit.HDR.mUHD-FRDS\Apollo.11.2019.BluRay.2160p.x265.10bit.HDR.mUHD-FRDS.mkv
    at makeError (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\node_modules\execa\lib\error.js:59:11)
    at Function.module.exports.sync (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\node_modules\execa\index.js:187:17)
    at getLinkPath (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\utils.js:29:21)
    at checkLinkExist (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\utils.js:36:17)
    at C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\index.js:191:17
    at Array.forEach (<anonymous>)
    at start (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\index.js:157:22)
    at C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\index.js:162:15
    at Array.forEach (<anonymous>)
    at start (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\index.js:157:22) {
  command: 'ls -i G:\\movies\\阿波罗11号.Apollo.11.2019.BluRay.2160p.x265.10bit.HDR.mUHD-FRDS\\Apollo.11.2019.BluRay.2160p.x265.10bit.HDR.mUHD-FRDS.mkv',
  exitCode: 1,
  exitCodeName: 'Unknown system error -1',
  stdout: '',
  stderr: "'ls' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\r\n���������ļ���",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined
}
TypeError: saveSourceAndDest.concat is not a function
    at saveSourceAndDest (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\updateSourceAndDest.js:25:47)
    at hardLink (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\lib\index.js:218:3)
    at Object.<anonymous> (C:\Users\ZhangYuan\AppData\Roaming\npm\node_modules\hlink\cli.js:63:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47`

**Comment by likun7981** [comment]
windows 可能近期支持不了，这个命令都是linux和mac上的，实在抱歉。

**Comment by likun7981** [comment]
暂时可能没有计划支持windows

**Comment by likun7981** [comment]
如果有强烈诉求，后面可以计划支持下

**Comment by likun7981** [comment]
使用windows的power shell 应该可以使用你可以试试

**Comment by likun7981** [comment]
![image](https://user-images.githubusercontent.com/13427467/103136380-d25cd680-46fa-11eb-8fc0-8b2574650183.png)


Windows 安装 git bash使用，测试可用 @gitnoobbbb
