### ISSUE TITLE
truenas下docker版报错

### ISSUE THREAD

**Issue by lingkai995** [likun7981/hlink#104]
<img width="1767" alt="image" src="https://user-images.githubusercontent.com/15700604/197405114-52b8201d-d51b-45db-b79a-a8eb190660fe.png">
更换了另一位大佬制作的PUID/PGID有用的版本，也不行，姑且排除权限问题？

`[22/10/23 16:55:03]  INFO  当前配置如下
[22/10/23 16:55:03]  INFO  包含规则: **/*.mp4,**/*.flv,**/*.f4v,**/*.webm,**/*.m4v,**/*.mov,**/*.cpk,**/*.dirac,**/*.3gp,**/*.3g2,**/*.rm,**/*.rmvb,**/*.wmv,**/*.avi,**/*.asf,**/*.mpg,**/*.mpeg,**/*.mpe,**/*.vob,**/*.mkv,**/*.ram,**/*.qt,**/*.fli,**/*.flc,**/*.mod,**/*.iso
[22/10/23 16:55:03]  INFO  排查规则: 无
[22/10/23 16:55:03]  INFO  缓存: 已关闭
[22/10/23 16:55:03]  INFO  保持原有目录结构: 是
[22/10/23 16:55:03]  INFO  为独立文件创建文件夹: 是
[22/10/23 16:55:03]  INFO  任务开始!
[22/10/23 16:55:03]  INFO  共计 1 个分析任务
[22/10/23 16:55:03]  INFO  执行分析任务: downloads/AV > AV
[22/10/23 16:55:03]  SUCCEED  分析任务执行完毕: downloads/AV > AV
[22/10/23 16:55:03]  INFO  共计 615 个文件
[22/10/23 16:55:03]  INFO  不满足配置的文件 534 个
[22/10/23 16:55:03]  INFO  已存在硬链的文件 0 个
[22/10/23 16:55:03]  INFO  需要硬链的文件 81 个
[22/10/23 16:55:03]  INFO  如果你看到这个消息，说明你的bash不支持格式化输入
[22/10/23 16:55:03]  ERROR  未知错误, 请完整截图咨询!
[22/10/23 16:55:03]  ERROR  Error: Command failed with exit code 1: ln /store/downloads/AV/2021年12月国产原创合集/91CM-214 MD-0196 LAX-0016 PM041 MDX-0231 血恋/血恋,1995,A,I,1080P,x264,DD2,0,粤国双语,内封简繁-FFansAIeNcE.mkv /store/AV/2021年12月国产原创合集/91CM-214 MD-0196 LAX-0016 PM041 MDX-0231 血恋
ln: /store/AV/2021年12月国产原创合集/91CM-214 MD-0196 LAX-0016 PM041 MDX-0231 血恋/血恋,1995,A,I,1080P,x264,DD2,0,粤国双语,内封简繁-FFansAIeNcE.mkv: Cross-device link
file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: ln /store/downloads/AV/2021年12月国产原创合集/91CM-214 MD-0196 LAX-0016 PM041 MDX-0231 血恋/血恋,1995,A,I,1080P,x264,DD2,0,粤国双语,内封简繁-FFansAIeNcE.mkv /store/AV/2021年12月国产原创合集/91CM-214 MD-0196 LAX-0016 PM041 MDX-0231 血恋
ln: /store/AV/2021年12月国产原创合集/91CM-214 MD-0196 LAX-0016 PM041 MDX-0231 血恋/血恋,1995,A,I,1080P,x264,DD2,0,粤国双语,内封简繁-FFansAIeNcE.mkv: Cross-device link
    at makeError (file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/local/lib/node_modules/hlink/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async link (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/link.js:21:9)
    at async callback (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:67:21)
    at async Promise.all (index 0)
    at async execAsyncByGroup (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/utils/execAsyncByGroup.js:7:9)
    at async hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:62:9)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5) {
  shortMessage: 'Command failed with exit code 1: ln /store/downloads/AV/2021年12月国产原创合集/91CM-214 MD-0196 LAX-0016 PM041 MDX-0231 血恋/血恋,1995,A,I,1080P,x264,DD2,0,粤国双语,内封简繁-FFansAIeNcE.mkv /store/AV/2021年12月国产原创合集/91CM-214 MD-0196 LAX-0016 PM041 MDX-0231 血恋',
  command: 'ln /store/downloads/AV/2021年12月国产原创合集/91CM-214 MD-0196 LAX-0016 PM041 MDX-0231 血恋/血恋,1995,A,I,1080P,x264,DD2,0,粤国双语,内封简繁-FFansAIeNcE.mkv /store/AV/2021年12月国产原创合集/91CM-214 MD-0196 LAX-0016 PM041 MDX-0231 血恋',
  escapedCommand: 'ln "/store/downloads/AV/2021年12月国产原创合集/91CM-214 MD-0196 LAX-0016 PM041 MDX-0231 血恋/血恋,1995,A,I,1080P,x264,DD2,0,粤国双语,内封简繁-FFansAIeNcE.mkv" "/store/AV/2021年12月国产原创合集/91CM-214 MD-0196 LAX-0016 PM041 MDX-0231 血恋"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'ln: /store/AV/2021年12月国产原创合集/91CM-214 MD-0196 LAX-0016 PM041 MDX-0231 血恋/血恋,1995,A,I,1080P,x264,DD2,0,粤国双语,内封简繁-FFansAIeNcE.mkv: Cross-device link',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

[22/10/23 16:55:03]  ERROR  任务执行出错，已终止`

**Comment by likun7981** [comment]
`Cross-device link` 跨盘或者跨共享文件夹

**Comment by lingkai995** [comment]
<img width="364" alt="image" src="https://user-images.githubusercontent.com/15700604/197531634-018fae47-4b5f-4f90-b6d2-d3245699832c.png">
但是实际上并没有跨盘和共享文件夹啊。
/mnt/store/downloads/AV #源
/mnt/store/AV #目的地

再次请大佬帮忙看看，感谢感谢

**Comment by Valpha** [comment]
老哥资源不错

**Comment by qwerty00007** [comment]
> <img alt="image" width="364" src="https://user-images.githubusercontent.com/15700604/197531634-018fae47-4b5f-4f90-b6d2-d3245699832c.png">
> 
> 但是实际上并没有跨盘和共享文件夹啊。 /mnt/store/downloads/AV #源 /mnt/store/AV #目的地
> 再次请大佬帮忙看看，感谢感谢

你 store 下的 av 和 downloads 是数据集吧， 不同的数据集准确来说应该是跨文件系统了，  也会报cross-device link。
那你应该怎么做？用新建文件夹就可以了。
