### ISSUE TITLE
2.0.6执行出现调用栈嵌套溢出问题

### ISSUE THREAD

**Issue by Imoagn** [likun7981/hlink#107]
[22/11/16 16:42:51]  SUCCEED  分析任务执行完毕: MediaDownloadsArchive > LinkedMediaLibrary
[22/11/16 16:44:37]  SUCCEED  分析任务执行完毕: PT > LinkedMediaLibrary
file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:39
        excludeFiles.push(...item.excludeFiles);
                     ^

RangeError: Maximum call stack size exceeded
    at file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:39:22
    at Array.forEach ()
    at hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:37:9)
    at runMicrotasks ()
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5)

一直使用hlink把PT下载和手动下载的内容，链接到资源库，2.0版本以来一直稳定。 （目前在用版本2.0.6）今天因为又增加了几部动画，再运行的时候，估计是因为文件数量或层级达到某个阈值了，开始报错了。

**Comment by zhouxiansheng** [comment]
我也遇到同样问题

报错代码：
[23/12/28 13:42:05]  INFO  当前配置如下
[23/12/28 13:42:05]  INFO  包含规则: 所有文件
[23/12/28 13:42:05]  INFO  排查规则: **/*.jpg,**/*.jpeg,**/*.png,**/*.nfo,**/*.txt,**/*.md5
[23/12/28 13:42:05]  INFO  缓存: 已打开
[23/12/28 13:42:05]  INFO  保持原有目录结构: 是
[23/12/28 13:42:05]  INFO  为独立文件创建文件夹: 是
[23/12/28 13:42:05]  INFO  任务开始!
[23/12/28 13:42:05]  INFO  共计 1 个分析任务
[23/12/28 13:42:05]  INFO  执行分析任务: downloads/X > linkX/X
[23/12/28 13:42:18]  SUCCEED  分析任务执行完毕: downloads/X > linkX/X
file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:39
        excludeFiles.push(...item.excludeFiles);
                     ^

RangeError: Maximum call stack size exceeded
    at file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:39:22
    at Array.forEach ()
    at hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:37:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5)

Node.js v18.16.0

[23/12/28 13:42:18]  ERROR  任务执行出错，已终止

**Comment by NickShee** [comment]
看这个 #141
