### ISSUE TITLE
请求扩大被扫描文件夹的文件数量

### ISSUE THREAD

**Issue by ArnyRen** [likun7981/hlink#111]
[22/12/19 16:49:06]  INFO  共计 1 个分析任务
[22/12/19 16:49:06]  INFO  执行分析任务: A > media/A
[22/12/19 16:53:12]  SUCCEED  分析任务执行完毕: A > media/A
file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:42
        parseResults.push(...item.parseResults);
                     ^

RangeError: Maximum call stack size exceeded
    at file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:42:22
    at Array.forEach ()
    at hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:37:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5)

[22/12/19 16:53:12]  ERROR  任务执行出错，已终止

目前A文件夹内包含126,685个文件 6,872个文件夹 总计57.7 TB。
我通常是将目录A内的视频文件通过hlink硬链接至/media/A中 然后通过刮削软件刮削分类后导入Emby。原A文件夹内继续PT保种上传。
A文件夹内几乎不可能手动对其管理，仅其下级目录就存在632个文件夹，后续继续PT下载也会自动创建新的文件夹。无法进行手动配置拆分操作。作者大大是否有办法修复hlink这个问题？拜托了，hlink对于pt党来说太好用了！

**Comment by DeepDarkV** [comment]
我也一直苦于文件数量无法使用这个工具进行硬链整理资源，看到作者在其他地方回复可分段处理，不知能否程序内置分段。

**Comment by likun7981** [comment]
> 我也一直苦于文件数量无法使用这个工具进行硬链整理资源，看到作者在其他地方回复可分段处理，不知能否程序内置分段。

暂时找到很好的方案，后面会关注
