### ISSUE TITLE
我这个报错是怎么回事？

### ISSUE THREAD

**Issue by heruxiaofu** [likun7981/hlink#122]
[23/01/26 13:23:13]  INFO  当前配置如下
[23/01/26 13:23:13]  INFO  包含规则: 所有文件
[23/01/26 13:23:13]  INFO  排查规则: 无
[23/01/26 13:23:13]  INFO  缓存: 已打开
[23/01/26 13:23:13]  INFO  保持原有目录结构: 是
[23/01/26 13:23:13]  INFO  为独立文件创建文件夹: 是
[23/01/26 13:23:13]  INFO  任务开始!
[23/01/26 13:23:13]  INFO  共计 1 个分析任务
[23/01/26 13:23:13]  INFO  执行分析任务: Drive/MOD > NAS/MOD
[23/01/26 13:23:26]  SUCCEED  分析任务执行完毕: Drive/MOD > NAS/MOD
file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:38
        waitLinkFiles.push(...item.waitLinkFiles);
                      ^

RangeError: Maximum call stack size exceeded
    at file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:38:23
    at Array.forEach ()
    at hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:37:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5)

Node.js v18.13.0

[23/01/26 13:23:26]  ERROR  任务执行出错，已终止

**Comment by likun7981** [comment]
文件太多，内存泄漏了，建议分批。目前暂时没有找到好的解决办法

**Comment by likun7981** [comment]
使用https://github.com/likun7981/hlink/issues/107 来追踪
