### ISSUE TITLE
这个报错的意思是？ INFO  如果你看到这个消息，说明你的bash不支持格式化输入？

### ISSUE THREAD

**Issue by gzbenson** [likun7981/hlink#139]
linux docker 运行的 hlink 

任务 jellyfin_hard_link 执行出错
[23/05/04 09:32:33]  INFO  当前配置如下
[23/05/04 09:32:33]  INFO  包含规则: **/*.mp4,**/*.flv,**/*.f4v,**/*.webm,**/*.m4v,**/*.mov,**/*.cpk,**/*.dirac,**/*.3gp,**/*.3g2,**/*.rm,**/*.rmvb,**/*.wmv,**/*.avi,**/*.asf,**/*.mpg,**/*.mpeg,**/*.mpe,**/*.vob,**/*.mkv,**/*.ram,**/*.qt,**/*.fli,**/*.flc,**/*.mod,**/*.iso,**/*.ts
[23/05/04 09:32:33]  INFO  排查规则: **/*.nfo,**/*.pdf,**/*.jpg,**/*.txt,**/*.xls
[23/05/04 09:32:33]  INFO  缓存: 已关闭
[23/05/04 09:32:33]  INFO  保持原有目录结构: 是
[23/05/04 09:32:33]  INFO  为独立文件创建文件夹: 是
[23/05/04 09:32:33]  INFO  任务开始!
[23/05/04 09:32:33]  INFO  共计 6 个分析任务
[23/05/04 09:32:33]  INFO  执行分析任务: source/tvshows > target/tvshows
[23/05/04 09:32:33]  INFO  执行分析任务: source/documentaries > target/documentaries
[23/05/04 09:32:33]  INFO  执行分析任务: source/movies > target/movies
[23/05/04 09:32:33]  INFO  执行分析任务: source/animations > target/animations
[23/05/04 09:32:33]  INFO  执行分析任务: source/education > target/education
[23/05/04 09:32:33]  SUCCEED  分析任务执行完毕: source/tvshows > target/tvshows
[23/05/04 09:32:33]  SUCCEED  分析任务执行完毕: source/education > target/education
[23/05/04 09:32:33]  SUCCEED  分析任务执行完毕: source/documentaries > target/documentaries
[23/05/04 09:32:33]  SUCCEED  分析任务执行完毕: source/movies > target/movies
[23/05/04 09:32:33]  SUCCEED  分析任务执行完毕: source/animations > target/animations
[23/05/04 09:32:33]  INFO  共计 30 个文件
[23/05/04 09:32:33]  INFO  不满足配置的文件 0 个
[23/05/04 09:32:33]  INFO  已存在硬链的文件 0 个
[23/05/04 09:32:33]  INFO  需要硬链的文件 30 个
[23/05/04 09:32:33]  INFO  如果你看到这个消息，说明你的bash不支持格式化输入
[23/05/04 09:32:33]  ERROR  未知错误, 请完整截图咨询!
[23/05/04 09:32:33]  ERROR  Error: EACCES: permission denied, mkdir '/share/target/tvshows/测试‘

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: EACCES: permission denied, mkdir '/share/target/tvshows/测试'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/share/target/tvshows/测试'
}

Node.js v18.14.1

[23/05/04 09:32:33]  ERROR  任务执行出错，已终止

**Comment by gzbenson** [comment]
处理了一下访问权限问题，报 Cross-device Link ，但是我源目录和目标目录都是在一个dataset 里面的啊 

[23/05/04 13:47:04]  INFO  如果你看到这个消息，说明你的bash不支持格式化输入
[23/05/04 13:47:04]  ERROR  未知错误, 请完整截图咨询!
[23/05/04 13:47:04]  ERROR  Error: Command failed with exit code 1: ln /share/source/documentaries/CCTV9.Aerial.China.S04.Complete.1080i.HDTV.H264-NGB/CCTV9.Aerial.China.S04E01.1080i.HDTV.H264-NGB.ts /share/target/documentaries/CCTV9.Aerial.China.S04.Complete.1080i.HDTV.H264-NGB
ln: /share/target/documentaries/CCTV9.Aerial.China.S04.Complete.1080i.HDTV.H264-NGB/CCTV9.Aerial.China.S04E01.1080i.HDTV.H264-NGB.ts: Cross-device link
file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: ln /share/source/documentaries/CCTV9.Aerial.China.S04.Complete.1080i.HDTV.H264-NGB/CCTV9.Aerial.China.S04E01.1080i.HDTV.H264-NGB.ts /share/target/documentaries/CCTV9.Aerial.China.S04.Complete.1080i.HDTV.H264-NGB
ln: /share/target/documentaries/CCTV9.Aerial.China.S04.Complete.1080i.HDTV.H264-NGB/CCTV9.Aerial.China.S04E01.1080i.HDTV.H264-NGB.ts: Cross-device link
    at makeError (file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/local/lib/node_modules/hlink/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async link (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/link.js:21:9)
    at async callback (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:67:21)
    at async Promise.all (index 0)
    at async execAsyncByGroup (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/utils/execAsyncByGroup.js:7:9)
    at async hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:62:9)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5) {
  shortMessage: 'Command failed with exit code 1: ln /share/source/documentaries/CCTV9.Aerial.China.S04.Complete.1080i.HDTV.H264-NGB/CCTV9.Aerial.China.S04E01.1080i.HDTV.H264-NGB.ts /share/target/documentaries/CCTV9.Aerial.China.S04.Complete.1080i.HDTV.H264-NGB',
  command: 'ln /share/source/documentaries/CCTV9.Aerial.China.S04.Complete.1080i.HDTV.H264-NGB/CCTV9.Aerial.China.S04E01.1080i.HDTV.H264-NGB.ts /share/target/documentaries/CCTV9.Aerial.China.S04.Complete.1080i.HDTV.H264-NGB',
  escapedCommand: 'ln "/share/source/documentaries/CCTV9.Aerial.China.S04.Complete.1080i.HDTV.H264-NGB/CCTV9.Aerial.China.S04E01.1080i.HDTV.H264-NGB.ts" "/share/target/documentaries/CCTV9.Aerial.China.S04.Complete.1080i.HDTV.H264-NGB"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'ln: /share/target/documentaries/CCTV9.Aerial.China.S04.Complete.1080i.HDTV.H264-NGB/CCTV9.Aerial.China.S04E01.1080i.HDTV.H264-NGB.ts: Cross-device link',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.14.1

**Comment by gzbenson** [comment]
已解决

**Comment by suixiang5731** [comment]
老哥，你那个permission denied问题怎么解决的，能详细说下吗

**Comment by suixiang5731** [comment]
> linux docker 运行的 hlink
> 
> 任务 jellyfin_hard_link 执行出错 [23/05/04 09:32:33] INFO 当前配置如下 [23/05/04 09:32:33] INFO 包含规则: **/*.mp4,**/_.flv,**/_.f4v,**/*.webm,**/_.m4v,**/_.mov,**/*.cpk,**/_.dirac,**/_.3gp,**/*.3g2,**/_.rm,**/_.rmvb,**/*.wmv,**/_.avi,**/_.asf,**/*.mpg,**/_.mpeg,**/_.mpe,**/*.vob,**/_.mkv,**/_.ram,**/*.qt,**/_.fli,**/_.flc,**/*.mod,**/_.iso,**/_.ts [23/05/04 09:32:33] INFO 排查规则: **/*.nfo,**/_.pdf,**/_.jpg,**/*.txt,**/*.xls [23/05/04 09:32:33] INFO 缓存: 已关闭 [23/05/04 09:32:33] INFO 保持原有目录结构: 是 [23/05/04 09:32:33] INFO 为独立文件创建文件夹: 是 [23/05/04 09:32:33] INFO 任务开始! [23/05/04 09:32:33] INFO 共计 6 个分析任务 [23/05/04 09:32:33] INFO 执行分析任务: source/tvshows > target/tvshows [23/05/04 09:32:33] INFO 执行分析任务: source/documentaries > target/documentaries [23/05/04 09:32:33] INFO 执行分析任务: source/movies > target/movies [23/05/04 09:32:33] INFO 执行分析任务: source/animations > target/animations [23/05/04 09:32:33] INFO 执行分析任务: source/education > target/education [23/05/04 09:32:33] SUCCEED 分析任务执行完毕: source/tvshows > target/tvshows [23/05/04 09:32:33] SUCCEED 分析任务执行完毕: source/education > target/education [23/05/04 09:32:33] SUCCEED 分析任务执行完毕: source/documentaries > target/documentaries [23/05/04 09:32:33] SUCCEED 分析任务执行完毕: source/movies > target/movies [23/05/04 09:32:33] SUCCEED 分析任务执行完毕: source/animations > target/animations [23/05/04 09:32:33] INFO 共计 30 个文件 [23/05/04 09:32:33] INFO 不满足配置的文件 0 个 [23/05/04 09:32:33] INFO 已存在硬链的文件 0 个 [23/05/04 09:32:33] INFO 需要硬链的文件 30 个 [23/05/04 09:32:33] INFO 如果你看到这个消息，说明你的bash不支持格式化输入 [23/05/04 09:32:33] ERROR 未知错误, 请完整截图咨询! [23/05/04 09:32:33] ERROR Error: EACCES: permission denied, mkdir '/share/target/tvshows/测试‘
> 
> node:internal/process/promises:288 triggerUncaughtException(err, true /* fromPromise */); ^
> 
> [Error: EACCES: permission denied, mkdir '/share/target/tvshows/测试'] { errno: -13, code: 'EACCES', syscall: 'mkdir', path: '/share/target/tvshows/测试' }
> 
> Node.js v18.14.1
> 
> [23/05/04 09:32:33] ERROR 任务执行出错，已终止

老哥，你这个permission denied问题怎么解决的，能详细说下吗

**Comment by kf1232133** [comment]
> > linux docker 运行的 hlink
> > 任务 jellyfin_hard_link 执行出错 [23/05/04 09:32:33] INFO 当前配置如下 [23/05/04 09:32:33] INFO 包含规则: **/*.mp4,**/_.flv,**/_.f4v,**/*.webm,**/_.m4v,**/_.mov,**/*.cpk,**/_.dirac,**/_.3gp,**/*.3g2,**/_.rm,**/_.rmvb,**/*.wmv,**/_.avi,**/_.asf,**/*.mpg,**/_.mpeg,**/_.mpe,**/*.vob,**/_.mkv,**/_.ram,**/*.qt,**/_.fli,**/_.flc,**/*.mod,**/_.iso,**/_.ts [23/05/04 09:32:33] INFO 排查规则: **/*.nfo,**/_.pdf,**/_.jpg,**/*.txt,**/*.xls [23/05/04 09:32:33] INFO 缓存: 已关闭 [23/05/04 09:32:33] INFO 保持原有目录结构: 是 [23/05/04 09:32:33] INFO 为独立文件创建文件夹: 是 [23/05/04 09:32:33] INFO 任务开始! [23/05/04 09:32:33] INFO 共计 6 个分析任务 [23/05/04 09:32:33] INFO 执行分析任务: source/tvshows > target/tvshows [23/05/04 09:32:33] INFO 执行分析任务: source/documentaries > target/documentaries [23/05/04 09:32:33] INFO 执行分析任务: source/movies > target/movies [23/05/04 09:32:33] INFO 执行分析任务: source/animations > target/animations [23/05/04 09:32:33] INFO 执行分析任务: source/education > target/education [23/05/04 09:32:33] SUCCEED 分析任务执行完毕: source/tvshows > target/tvshows [23/05/04 09:32:33] SUCCEED 分析任务执行完毕: source/education > target/education [23/05/04 09:32:33] SUCCEED 分析任务执行完毕: source/documentaries > target/documentaries [23/05/04 09:32:33] SUCCEED 分析任务执行完毕: source/movies > target/movies [23/05/04 09:32:33] SUCCEED 分析任务执行完毕: source/animations > target/animations [23/05/04 09:32:33] INFO 共计 30 个文件 [23/05/04 09:32:33] INFO 不满足配置的文件 0 个 [23/05/04 09:32:33] INFO 已存在硬链的文件 0 个 [23/05/04 09:32:33] INFO 需要硬链的文件 30 个 [23/05/04 09:32:33] INFO 如果你看到这个消息，说明你的bash不支持格式化输入 [23/05/04 09:32:33] ERROR 未知错误, 请完整截图咨询! [23/05/04 09:32:33] ERROR Error: EACCES: permission denied, mkdir '/share/target/tvshows/测试‘
> > node:internal/process/promises:288 triggerUncaughtException(err, true /* fromPromise */); ^
> > [Error: EACCES: permission denied, mkdir '/share/target/tvshows/测试'] { errno: -13, code: 'EACCES', syscall: 'mkdir', path: '/share/target/tvshows/测试' }
> > Node.js v18.14.1
> > [23/05/04 09:32:33] ERROR 任务执行出错，已终止
> 
> 老哥，你这个permission denied问题怎么解决的，能详细说下吗

docker只映射一个源目录和下载目录的共同父目录，不要分别映射两个目录
