### ISSUE TITLE
报错反馈

### ISSUE THREAD

**Issue by RenMu-V** [likun7981/hlink#140]
`[23/05/04 11:45:19]  INFO  当前配置如下
[23/05/04 11:45:19]  INFO  包含规则: **/*.mp4,**/*.flv,**/*.f4v,**/*.webm,**/*.m4v,**/*.mov,**/*.cpk,**/*.dirac,**/*.3gp,**/*.3g2,**/*.rm,**/*.rmvb,**/*.wmv,**/*.avi,**/*.asf,**/*.mpg,**/*.mpeg,**/*.mpe,**/*.vob,**/*.mkv,**/*.ram,**/*.qt,**/*.fli,**/*.flc,**/*.mod,**/*.iso
[23/05/04 11:45:19]  INFO  排查规则: 无
[23/05/04 11:45:19]  INFO  缓存: 已关闭
[23/05/04 11:45:19]  INFO  保持原有目录结构: 是
[23/05/04 11:45:19]  INFO  为独立文件创建文件夹: 是
[23/05/04 11:45:19]  INFO  任务开始!
[23/05/04 11:45:19]  INFO  共计 1 个分析任务
[23/05/04 11:45:19]  INFO  执行分析任务: 韩国三级 > 韩国三级/刮削
[23/05/04 11:45:19]  SUCCEED  分析任务执行完毕: 韩国三级 > 韩国三级/刮削
[23/05/04 11:45:19]  INFO  共计 491 个文件
[23/05/04 11:45:19]  INFO  不满足配置的文件 0 个
[23/05/04 11:45:19]  INFO  已存在硬链的文件 417 个
[23/05/04 11:45:19]  INFO  需要硬链的文件 74 个
[23/05/04 11:45:19]  INFO  如果你看到这个消息，说明你的bash不支持格式化输入
[23/05/04 11:45:19]  ERROR  未知错误, 请完整截图咨询!
[23/05/04 11:45:19]  ERROR  Error: Command failed with exit code 1: ln /18t/韩国三级/korean2020part1/å¦»å­?ç??ä¸?ç??.Wifes.World.2020.HD720P.X264.AAC.Korean.CHS.mp4 /18t/韩国三级/刮削/korean2020part1
ln: /18t/韩国三级/korean2020part1/å¦»å­?ç??ä¸?ç??.Wifes.World.2020.HD720P.X264.AAC.Korean.CHS.mp4: No such file or directory
file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: ln /18t/韩国三级/korean2020part1/å¦»å­?ç??ä¸?ç??.Wifes.World.2020.HD720P.X264.AAC.Korean.CHS.mp4 /18t/韩国三级/刮削/korean2020part1
ln: /18t/韩国三级/korean2020part1/å¦»å­?ç??ä¸?ç??.Wifes.World.2020.HD720P.X264.AAC.Korean.CHS.mp4: No such file or directory
    at makeError (file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/local/lib/node_modules/hlink/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async link (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/link.js:21:9)
    at async callback (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:67:21)
    at async Promise.all (index 1)
    at async execAsyncByGroup (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/utils/execAsyncByGroup.js:7:9)
    at async hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:62:9)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5) {
  shortMessage: 'Command failed with exit code 1: ln /18t/韩国三级/korean2020part1/å¦»å­?ç??ä¸?ç??.Wifes.World.2020.HD720P.X264.AAC.Korean.CHS.mp4 /18t/韩国三级/刮削/korean2020part1',
  command: 'ln /18t/韩国三级/korean2020part1/å¦»å­?ç??ä¸?ç??.Wifes.World.2020.HD720P.X264.AAC.Korean.CHS.mp4 /18t/韩国三级/刮削/korean2020part1',
  escapedCommand: 'ln "/18t/韩国三级/korean2020part1/å¦»å­?ç??ä¸?ç??.Wifes.World.2020.HD720P.X264.AAC.Korean.CHS.mp4" "/18t/韩国三级/刮削/korean2020part1"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'ln: /18t/韩国三级/korean2020part1/å¦»å­?ç??ä¸?ç??.Wifes.World.2020.HD720P.X264.AAC.Korean.CHS.mp4: No such file or directory',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.14.1

[23/05/04 11:45:19]  ERROR  任务执行出错，已终止`
文件正常能播放

**Comment by likun7981** [comment]
`No such file or directory` 文件未找到
