### ISSUE TITLE
报错反馈，疑似是因为文件数量太大导致

### ISSUE THREAD

**Issue by casselluu** [likun7981/hlink#141]
[23/05/10 09:19:25]  SUCCEED  分析任务执行完毕: Downloads/有声书 > Audio/Book
file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:42
        parseResults.push(...item.parseResults);
                     ^

RangeError: Maximum call stack size exceeded
    at file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:42:22
    at Array.forEach ()
    at hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:37:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5)

Node.js v18.14.1

[23/05/10 09:19:26]  ERROR  任务执行出错，已终止

约有130本有声书，音频文件估计有20万个。
docker部署，配置如下
pathsmapping: {'/Media/Downloads/有声书' : '/Media/Audio/Book'},  
include: [],
  exclude: ['!qB','tmp'], 
 keepDirStruct: true, 
 openCache: false,
 mkdirIfSingle: true,  
deleteDir: false,

**Comment by likun7981** [comment]
暂时没有好的解决办法。麻烦先手动拆分一下

**Comment by NickShee** [comment]
同样问题，留个mark

**Comment by ReddotCleaner** [comment]
> 同样问题，留个mark

https://github.com/likun7981/hlink/issues/201 已尝试修复，可以试试看
