### ISSUE TITLE
报错：Command failed with exit code 1 (EPERM)

### ISSUE THREAD

**Issue by virtue050** [likun7981/hlink#15]
运行建立硬链接的时候报错，提示：Command failed with exit code 1 (EPERM)

Error: Command failed with exit code 1 (EPERM): ln /opt/movie/avdc/failed/mywife-1702.mp4 /opt/vdieo/failed
    at makeError (/usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59:11)
    at Function.module.exports.sync (/usr/local/lib/node_modules/hlink/node_modules/execa/index.js:187:17)
    at /usr/local/lib/node_modules/hlink/lib/index.js:200:19
    at Array.forEach (<anonymous>)
    at start (/usr/local/lib/node_modules/hlink/lib/index.js:159:22)
    at /usr/local/lib/node_modules/hlink/lib/index.js:164:17
    at Array.forEach (<anonymous>)
    at start (/usr/local/lib/node_modules/hlink/lib/index.js:159:22)
    at hardLink (/usr/local/lib/node_modules/hlink/lib/index.js:221:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/hlink/cli.js:63:1) {
  command: 'ln /opt/movie/avdc/failed/mywife-1702.mp4 /opt/vdieo/failed',
  exitCode: 1,
  exitCodeName: 'EPERM',
  stdout: '',
  stderr: "ln: failed to create hard link '/opt/vdieo/failed/mywife-1702.mp4' => '/opt/movie/avdc/failed/mywife-1702.mp4': Invalid cross-device link",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined

**Comment by likun7981** [comment]
```
stderr: "ln: failed to create hard link '/opt/vdieo/failed/mywife-1702.mp4' => '/opt/movie/avdc/failed/mywife-1702.mp4': Invalid cross-device link",
```

`cross-device` 跨盘了
