### ISSUE TITLE
大佬今天突然报错了，不知道除了什么问题

### ISSUE THREAD

**Issue by Erfeet** [likun7981/hlink#151]
ERROR  未知错误, 请完整截图咨询!
[23/07/23 10:50:03]  ERROR  Error: Command failed with ENOMEM: ln /hlink/剧集/【高清剧集网 www.BTHDTV.com】弥留之国的爱丽丝 第二季[杜比视界版本][全8集][简繁英字幕].Alice.in.Borderland.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DV.H.265-BlackTV/Alice.in.Borderland.S02E01.Episode.1.2160p.NF.WEB-DL.DDP.5.1.Atmos.DV.H.265-BlackTV.mp4 /hlink/hlink/剧集/【高清剧集网 www.BTHDTV.com】弥留之国的爱丽丝 第二季[杜比视界版本][全8集][简繁英字幕].Alice.in.Borderland.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DV.H.265-BlackTV
spawn ENOMEM
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error: Command failed with ENOMEM: ln /hlink/剧集/【高清剧集网 www.BTHDTV.com】弥留之国的爱丽丝 第二季[杜比视界版本][全8集][简繁英字幕].Alice.in.Borderland.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DV.H.265-BlackTV/Alice.in.Borderland.S02E01.Episode.1.2160p.NF.WEB-DL.DDP.5.1.Atmos.DV.H.265-BlackTV.mp4 /hlink/hlink/剧集/【高清剧集网 www.BTHDTV.com】弥留之国的爱丽丝 第二季[杜比视界版本][全8集][简繁英字幕].Alice.in.Borderland.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DV.H.265-BlackTV
spawn ENOMEM
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:757:9)
    at execa (file:///usr/local/lib/node_modules/hlink/node_modules/execa/index.js:84:26)
    at link (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/link.js:21:15)
    at async callback (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:67:21)
    at async Promise.all (index 0)
    at async execAsyncByGroup (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/utils/execAsyncByGroup.js:7:9)
    at async hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:62:9)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5) {
  errno: -12,
  code: 'ENOMEM',
  syscall: 'spawn',
  originalMessage: 'spawn ENOMEM',
  shortMessage: 'Command failed with ENOMEM: ln /hlink/剧集/【高清剧集网 www.BTHDTV.com】弥留之国的爱丽丝 第二季[杜比视界版本][全8集][简繁英字幕].Alice.in.Borderland.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DV.H.265-BlackTV/Alice.in.Borderland.S02E01.Episode.1.2160p.NF.WEB-DL.DDP.5.1.Atmos.DV.H.265-BlackTV.mp4 /hlink/hlink/剧集/【高清剧集网 www.BTHDTV.com】弥留之国的爱丽丝 第二季[杜比视界版本][全8集][简繁英字幕].Alice.in.Borderland.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DV.H.265-BlackTV\n' +
    'spawn ENOMEM',
  command: 'ln /hlink/剧集/【高清剧集网 www.BTHDTV.com】弥留之国的爱丽丝 第二季[杜比视界版本][全8集][简繁英字幕].Alice.in.Borderland.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DV.H.265-BlackTV/Alice.in.Borderland.S02E01.Episode.1.2160p.NF.WEB-DL.DDP.5.1.Atmos.DV.H.265-BlackTV.mp4 /hlink/hlink/剧集/【高清剧集网 www.BTHDTV.com】弥留之国的爱丽丝 第二季[杜比视界版本][全8集][简繁英字幕].Alice.in.Borderland.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DV.H.265-BlackTV',
  escapedCommand: 'ln "/hlink/剧集/【高清剧集网 www.BTHDTV.com】弥留之国的爱丽丝 第二季[杜比视界版本][全8集][简繁英字幕].Alice.in.Borderland.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DV.H.265-BlackTV/Alice.in.Borderland.S02E01.Episode.1.2160p.NF.WEB-DL.DDP.5.1.Atmos.DV.H.265-BlackTV.mp4" "/hlink/hlink/剧集/【高清剧集网 www.BTHDTV.com】弥留之国的爱丽丝 第二季[杜比视界版本][全8集][简繁英字幕].Alice.in.Borderland.S02.2160p.NF.WEB-DL.DDP.5.1.Atmos.DV.H.265-BlackTV"',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  all: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.16.0

[23/07/23 10:50:03]  ERROR  任务执行出错，已终止

**Comment by Erfeet** [comment]
之前都是正常的

**Comment by likun7981** [comment]
重试也报错？

**Comment by Erfeet** [comment]
时不时的就这样

**Comment by Erfeet** [comment]
[23/08/06 09:49:06]  INFO  如果你看到这个消息，说明你的bash不支持格式化输入
[23/08/06 09:49:08]  ERROR  未知错误, 请完整截图咨询!
[23/08/06 09:49:08]  ERROR  Error: Command failed with exit code 1: ln /download/剧集/Alice.in.Borderland.S02.JAPANESE.2160p.NF.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-XEBEC[rartv]/Alice.in.Borderland.S02E02.2160p.NF.WEB-DL.DDP5.1.Atmos.HDR.HEVC-XEBEC.mkv /hlink/剧集/Alice.in.Borderland.S02.JAPANESE.2160p.NF.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-XEBEC[rartv]
ln: /hlink/剧集/Alice.in.Borderland.S02.JAPANESE.2160p.NF.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-XEBEC[rartv]/Alice.in.Borderland.S02E02.2160p.NF.WEB-DL.DDP5.1.Atmos.HDR.HEVC-XEBEC.mkv: Cross-device link
file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: ln /download/剧集/Alice.in.Borderland.S02.JAPANESE.2160p.NF.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-XEBEC[rartv]/Alice.in.Borderland.S02E02.2160p.NF.WEB-DL.DDP5.1.Atmos.HDR.HEVC-XEBEC.mkv /hlink/剧集/Alice.in.Borderland.S02.JAPANESE.2160p.NF.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-XEBEC[rartv]
ln: /hlink/剧集/Alice.in.Borderland.S02.JAPANESE.2160p.NF.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-XEBEC[rartv]/Alice.in.Borderland.S02E02.2160p.NF.WEB-DL.DDP5.1.Atmos.HDR.HEVC-XEBEC.mkv: Cross-device link
    at makeError (file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/local/lib/node_modules/hlink/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async link (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/link.js:21:9)
    at async callback (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:67:21)
    at async Promise.all (index 1)
    at async execAsyncByGroup (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/utils/execAsyncByGroup.js:7:9)
    at async hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:62:9)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5) {
  shortMessage: 'Command failed with exit code 1: ln /download/剧集/Alice.in.Borderland.S02.JAPANESE.2160p.NF.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-XEBEC[rartv]/Alice.in.Borderland.S02E02.2160p.NF.WEB-DL.DDP5.1.Atmos.HDR.HEVC-XEBEC.mkv /hlink/剧集/Alice.in.Borderland.S02.JAPANESE.2160p.NF.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-XEBEC[rartv]',
  command: 'ln /download/剧集/Alice.in.Borderland.S02.JAPANESE.2160p.NF.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-XEBEC[rartv]/Alice.in.Borderland.S02E02.2160p.NF.WEB-DL.DDP5.1.Atmos.HDR.HEVC-XEBEC.mkv /hlink/剧集/Alice.in.Borderland.S02.JAPANESE.2160p.NF.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-XEBEC[rartv]',
  escapedCommand: 'ln "/download/剧集/Alice.in.Borderland.S02.JAPANESE.2160p.NF.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-XEBEC[rartv]/Alice.in.Borderland.S02E02.2160p.NF.WEB-DL.DDP5.1.Atmos.HDR.HEVC-XEBEC.mkv" "/hlink/剧集/Alice.in.Borderland.S02.JAPANESE.2160p.NF.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-XEBEC[rartv]"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'ln: /hlink/剧集/Alice.in.Borderland.S02.JAPANESE.2160p.NF.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-XEBEC[rartv]/Alice.in.Borderland.S02E02.2160p.NF.WEB-DL.DDP5.1.Atmos.HDR.HEVC-XEBEC.mkv: Cross-device link',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.16.0
现在出现的新的报错

**Comment by Erfeet** [comment]
[23/08/06 11:56:45]  INFO  任务开始!
[23/08/06 11:56:45]  INFO  共计 1 个分析任务
[23/08/06 11:56:45]  INFO  执行分析任务: download > hlink
[23/08/06 11:56:49]  SUCCEED  分析任务执行完毕: download > hlink
[23/08/06 11:56:49]  INFO  共计 1956 个文件
[23/08/06 11:56:49]  INFO  不满足配置的文件 344 个
[23/08/06 11:56:49]  INFO  已存在硬链的文件 0 个
[23/08/06 11:56:49]  INFO  需要硬链的文件 1612 个
[23/08/06 11:56:49]  INFO  如果你看到这个消息，说明你的bash不支持格式化输入
[23/08/06 11:56:49]  ERROR  未知错误, 请完整截图咨询!
[23/08/06 11:56:49]  ERROR  Error: Command failed with ENOMEM: ln /download/剧集/Alice.in.Borderland.S02.JAPANESE.2160p.NF.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-XEBEC[rartv]/Alice.in.Borderland.S02E01.2160p.NF.WEB-DL.DDP5.1.Atmos.HDR.HEVC-XEBEC.mkv /hlink/剧集/Alice.in.Borderland.S02.JAPANESE.2160p.NF.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-XEBEC[rartv]

spawn ENOMEM
Error: Command failed with ENOMEM: ln /download/剧集/Alice.in.Borderland.S02.JAPANESE.2160p.NF.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-XEBEC[rartv]/Alice.in.Borderland.S02E01.2160p.NF.WEB-DL.DDP5.1.Atmos.HDR.HEVC-XEBEC.mkv /hlink/剧集/Alice.in.Borderland.S02.JAPANESE.2160p.NF.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-XEBEC[rartv]

spawn ENOMEM
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:757:9)
    at execa (file:///usr/local/lib/node_modules/hlink/node_modules/execa/index.js:84:26)
    at link (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/link.js:21:15)
    at async callback (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:67:21)
    at async Promise.all (index 0)
    at async execAsyncByGroup (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/utils/execAsyncByGroup.js:7:9)
    at async hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:62:9)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5)
    at async startTask (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/app/dist/kit/TaskSDK.js:245:17)
[23/08/06 11:57:00]  SUCCEED  hlink serve started http://undefined:9090
[23/08/06 11:57:00]  SUCCEED  已取消计划任务 影视
[23/08/06 11:57:00]  SUCCEED  计划任务影视已开启：loop | 3000
[23/08/06 11:57:00]  INFO  当前配置如下
[23/08/06 11:57:00]  INFO  包含规则: **/*.mp4,**/*.flv,**/*.f4v,**/*.webm,**/*.m4v,**/*.mov,**/*.cpk,**/*.dirac,**/*.3gp,**/*.3g2,**/*.rm,**/*.rmvb,**/*.wmv,**/*.avi,**/*.asf,**/*.mpg,**/*.mpeg,**/*.mpe,**/*.vob,**/*.mkv,**/*.ram,**/*.qt,**/*.fli,**/*.flc,**/*.mod,**/*.iso,**/*.bdmv,**/*.clpi,**/*.mpls,**/*.m2ts,**/*.crt,**/*.scas,**/*.ocmp,**/*.bdjo,**/*.nfo,**/*.jar,**/*.xml,**/*.jpg
[23/08/06 11:57:00]  INFO  排查规则: 无
[23/08/06 11:57:00]  INFO  缓存: 已关闭
[23/08/06 11:57:00]  INFO  保持原有目录结构: 是
[23/08/06 11:57:00]  INFO  为独立文件创建文件夹: 是
[23/08/06 11:57:00]  INFO  任务开始!
[23/08/06 11:57:00]  INFO  共计 1 个分析任务
[23/08/06 11:57:00]  INFO  执行分析任务: download > hlink
Error: Command failed with ENOMEM: ls -iRFL /download

spawn ENOMEM
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:757:9)
    at execa (file:///usr/local/lib/node_modules/hlink/node_modules/execa/index.js:84:26)
    at lsirf (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/core/lsirfl.js:8:28)
    at async parseLs (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/core/parseLsirfl.js:7:17)
    at async analyse (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/analyse.js:14:26)
    at async Promise.all (index 0)
    at async hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:27:6)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5)
    at async startTask (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/app/dist/kit/TaskSDK.js:245:17)
[23/08/06 11:57:18]  SUCCEED  hlink serve started http://undefined:9090
[23/08/06 11:57:18]  SUCCEED  已取消计划任务 影视
[23/08/06 11:57:18]  SUCCEED  计划任务影视已开启：loop | 3000
[23/08/06 11:57:18]  INFO  当前配置如下
[23/08/06 11:57:18]  INFO  包含规则: **/*.mp4,**/*.flv,**/*.f4v,**/*.webm,**/*.m4v,**/*.mov,**/*.cpk,**/*.dirac,**/*.3gp,**/*.3g2,**/*.rm,**/*.rmvb,**/*.wmv,**/*.avi,**/*.asf,**/*.mpg,**/*.mpeg,**/*.mpe,**/*.vob,**/*.mkv,**/*.ram,**/*.qt,**/*.fli,**/*.flc,**/*.mod,**/*.iso,**/*.bdmv,**/*.clpi,**/*.mpls,**/*.m2ts,**/*.crt,**/*.scas,**/*.ocmp,**/*.bdjo,**/*.nfo,**/*.jar,**/*.xml,**/*.jpg
[23/08/06 11:57:18]  INFO  排查规则: 无
[23/08/06 11:57:18]  INFO  缓存: 已关闭
[23/08/06 11:57:18]  INFO  保持原有目录结构: 是
[23/08/06 11:57:18]  INFO  为独立文件创建文件夹: 是
[23/08/06 11:57:18]  INFO  任务开始!
[23/08/06 11:57:18]  INFO  共计 1 个分析任务
[23/08/06 11:57:18]  INFO  执行分析任务: download > hlink
Error: Command failed with ENOMEM: ls -iRFL /download

spawn ENOMEM
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:757:9)
    at execa (file:///usr/local/lib/node_modules/hlink/node_modules/execa/index.js:84:26)
    at lsirf (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/core/lsirfl.js:8:28)
    at async parseLs (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/core/parseLsirfl.js:7:17)
    at async analyse (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/analyse.js:14:26)
    at async Promise.all (index 0)
    at async hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:27:6)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5)
    at async startTask (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/app/dist/kit/TaskSDK.js:245:17)
[23/08/06 11:57:48]  SUCCEED  hlink serve started http://undefined:9090
[23/08/06 11:57:48]  SUCCEED  已取消计划任务 影视
[23/08/06 11:57:48]  SUCCEED  计划任务影视已开启：loop | 3000
[23/08/06 11:57:48]  INFO  当前配置如下
[23/08/06 11:57:48]  INFO  包含规则: **/*.mp4,**/*.flv,**/*.f4v,**/*.webm,**/*.m4v,**/*.mov,**/*.cpk,**/*.dirac,**/*.3gp,**/*.3g2,**/*.rm,**/*.rmvb,**/*.wmv,**/*.avi,**/*.asf,**/*.mpg,**/*.mpeg,**/*.mpe,**/*.vob,**/*.mkv,**/*.ram,**/*.qt,**/*.fli,**/*.flc,**/*.mod,**/*.iso,**/*.bdmv,**/*.clpi,**/*.mpls,**/*.m2ts,**/*.crt,**/*.scas,**/*.ocmp,**/*.bdjo,**/*.nfo,**/*.jar,**/*.xml,**/*.jpg
[23/08/06 11:57:48]  INFO  排查规则: 无
[23/08/06 11:57:48]  INFO  缓存: 已关闭
[23/08/06 11:57:48]  INFO  保持原有目录结构: 是
[23/08/06 11:57:48]  INFO  为独立文件创建文件夹: 是
[23/08/06 11:57:48]  INFO  任务开始!
[23/08/06 11:57:48]  INFO  共计 1 个分析任务
[23/08/06 11:57:48]  INFO  执行分析任务: download > hlink
Error: Command failed with ENOMEM: ls -iRFL /download

spawn ENOMEM
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:757:9)
    at execa (file:///usr/local/lib/node_modules/hlink/node_modules/execa/index.js:84:26)
    at lsirf (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/core/lsirfl.js:8:28)
    at async parseLs (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/core/parseLsirfl.js:7:17)
    at async analyse (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/analyse.js:14:26)
    at async Promise.all (index 0)
    at async hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:27:6)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5)
    at async startTask (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/app/dist/kit/TaskSDK.js:245:17)

**Comment by Erfeet** [comment]
修着修着变成这样了/哭
