### ISSUE TITLE
报错Error: Command failed with exit code 1

### ISSUE THREAD

**Issue by engchs** [likun7981/hlink#156]
打算把photos备份的视频，同步到emby的视频文件夹下，可以在电视上查看，报如下错误。看到有帖子说“Cross-device”是跨盘了，确定了下两个文件夹都是在同一个存储空间下的。

[23/10/17 09:26:53]  ERROR  未知错误, 请完整截图咨询!
[23/10/17 09:26:53]  ERROR  Error: Command failed with exit code 1: ln /home_source/全部照片待整理/(null)_WC-EditVideo_1.mp4 /volume3/video/family/成长记录/全部照片待整理
ln: /volume3/video/family/成长记录/全部照片待整理/(null)_WC-EditVideo_1.mp4: Cross-device link
file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: ln /home_source/全部照片待整理/(null)_WC-EditVideo_1.mp4 /volume3/video/family/成长记录/全部照片待整理
ln: /volume3/video/family/成长记录/全部照片待整理/(null)_WC-EditVideo_1.mp4: Cross-device link
    at makeError (file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/local/lib/node_modules/hlink/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async link (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/link.js:21:9)
    at async callback (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:67:21)
    at async Promise.all (index 0)
    at async execAsyncByGroup (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/utils/execAsyncByGroup.js:7:9)
    at async hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:62:9)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5) {
  shortMessage: 'Command failed with exit code 1: ln /home_source/全部照片待整理/(null)_WC-EditVideo_1.mp4 /volume3/video/family/成长记录/全部照片待整理',
  command: 'ln /home_source/全部照片待整理/(null)_WC-EditVideo_1.mp4 /volume3/video/family/成长记录/全部照片待整理',
  escapedCommand: 'ln "/home_source/全部照片待整理/(null)_WC-EditVideo_1.mp4" "/volume3/video/family/成长记录/全部照片待整理"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'ln: /volume3/video/family/成长记录/全部照片待整理/(null)_WC-EditVideo_1.mp4: Cross-device link',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.16.0

[23/10/17 09:26:53]  ERROR  任务执行出错，已终止

**Comment by likun7981** [comment]
看到 cross-device字样就是跨盘 或者 跨共享目录
