### ISSUE TITLE
威联通docker部署，运行报错。

### ISSUE THREAD

**Issue by cxd0812** [likun7981/hlink#162]
我是在威联通docker内部署的，运行后提示 Cross-device link 错误。首先，我没有用SSD缓存，源目录与目标目录都在一个文件系统内。

下面是完整的日志，麻烦大神看下，感谢了。

[24/01/24 03:07:15]  INFO  当前配置如下
[24/01/24 03:07:15]  INFO  包含规则: **/*.mp4
[24/01/24 03:07:15]  INFO  排查规则: 无
[24/01/24 03:07:15]  INFO  缓存: 已关闭
[24/01/24 03:07:15]  INFO  保持原有目录结构: 否
[24/01/24 03:07:15]  INFO  为独立文件创建文件夹: 是
[24/01/24 03:07:15]  INFO  任务开始!
[24/01/24 03:07:15]  INFO  共计 1 个分析任务
[24/01/24 03:07:15]  INFO  执行分析任务: download2/gen > movie2
[24/01/24 03:07:15]  SUCCEED  分析任务执行完毕: download2/gen > movie2
[24/01/24 03:07:15]  INFO  共计 1004 个文件
[24/01/24 03:07:15]  INFO  不满足配置的文件 1003 个
[24/01/24 03:07:15]  INFO  已存在硬链的文件 0 个
[24/01/24 03:07:15]  INFO  需要硬链的文件 1 个
[24/01/24 03:07:15]  INFO  如果你看到这个消息，说明你的bash不支持格式化输入
[24/01/24 03:07:15]  ERROR  未知错误, 请完整截图咨询!
[24/01/24 03:07:15]  ERROR  Error: Command failed with exit code 1: ln /home/download2/gen/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo.mp4 /home/movie2/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo
ln: /home/movie2/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo.mp4: Cross-device link
file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: ln /home/download2/gen/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo.mp4 /home/movie2/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo
ln: /home/movie2/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo.mp4: Cross-device link
    at makeError (file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/local/lib/node_modules/hlink/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async link (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/link.js:21:9)
    at async callback (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:67:21)
    at async Promise.all (index 0)
    at async execAsyncByGroup (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/utils/execAsyncByGroup.js:7:9)
    at async hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:62:9)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5) {
  shortMessage: 'Command failed with exit code 1: ln /home/download2/gen/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo.mp4 /home/movie2/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo',
  command: 'ln /home/download2/gen/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo.mp4 /home/movie2/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo',
  escapedCommand: 'ln "/home/download2/gen/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo.mp4" "/home/movie2/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'ln: /home/movie2/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo/[莫斯科行动].Moscow.Mission.2023.2160p.60fps.WEB-DL.HEVC.10bit.DDP5.1.3Audios-QHstudIo.mp4: Cross-device link',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.16.0

[24/01/24 03:07:15]  ERROR  任务执行出错，已终止

**Comment by alei643** [comment]
目前测试了多次，应该是不可以跨盘建立硬链，源路径和目标路径均位于一个硬盘就可以正常建立硬链。
