### ISSUE TITLE
bash不支持格式化输入

### ISSUE THREAD

**Issue by JadePureOne** [likun7981/hlink#178]
[24/04/07 21:59:07]  INFO  当前配置如下
[24/04/07 21:59:07]  INFO  包含规则: **/*.txt,**/*.3g2,**/*.3gp,**/*.asf,**/*.ass,**/*.avi,**/*.cpk,**/*.cue,**/*.dirac,**/*.f4v,**/*.flac,**/*.flc,**/*.fli,**/*.flv,**/*.jpg,**/*.iso,**/*.jpg,**/*.m4v,**/*.mkv,**/*.mka,**/*.mod,**/*.mov,**/*.mp4,**/*.mpeg,**/*.mpe,**/*.mpg,**/*.nfo,**/*.qt,**/*.ram,**/*.rm,**/*.rmvb,**/*.vob,**/*.webm,**/*.wmv
[24/04/07 21:59:07]  INFO  排查规则: 无
[24/04/07 21:59:07]  INFO  缓存: 已关闭
[24/04/07 21:59:07]  INFO  保持原有目录结构: 是
[24/04/07 21:59:07]  INFO  为独立文件创建文件夹: 是
[24/04/07 21:59:07]  INFO  任务开始!
[24/04/07 21:59:07]  INFO  共计 1 个分析任务
[24/04/07 21:59:07]  INFO  执行分析任务: biliCollention/mine-default > media/硬链接/biliCollection/mine
[24/04/07 21:59:09]  SUCCEED  分析任务执行完毕: biliCollention/mine-default > media/硬链接/biliCollection/mine
[24/04/07 21:59:09]  INFO  共计 5004 个文件
[24/04/07 21:59:09]  INFO  不满足配置的文件 0 个
[24/04/07 21:59:09]  INFO  已存在硬链的文件 0 个
[24/04/07 21:59:09]  INFO  需要硬链的文件 5004 个
[24/04/07 21:59:09]  INFO  如果你看到这个消息，说明你的bash不支持格式化输入
[24/04/07 21:59:10]  ERROR  未知错误, 请完整截图咨询!
[24/04/07 21:59:10]  ERROR  Error: Command failed with exit code 1: ln /biliCollention/mine-default/BV1184y1a7ya-poster.jpg /media/硬链接/biliCollection/mine/BV1184y1a7ya-poster
ln: /media/硬链接/biliCollection/mine/BV1184y1a7ya-poster/BV1184y1a7ya-poster.jpg: Cross-device link
file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: ln /biliCollention/mine-default/BV1184y1a7ya-poster.jpg /media/硬链接/biliCollection/mine/BV1184y1a7ya-poster
ln: /media/硬链接/biliCollection/mine/BV1184y1a7ya-poster/BV1184y1a7ya-poster.jpg: Cross-device link
    at makeError (file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/local/lib/node_modules/hlink/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async link (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/link.js:21:9)
    at async callback (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:67:21)
    at async Promise.all (index 0)
    at async execAsyncByGroup (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/utils/execAsyncByGroup.js:7:9)
    at async hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:62:9)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5) {
  shortMessage: 'Command failed with exit code 1: ln /biliCollention/mine-default/BV1184y1a7ya-poster.jpg /media/硬链接/biliCollection/mine/BV1184y1a7ya-poster',
  command: 'ln /biliCollention/mine-default/BV1184y1a7ya-poster.jpg /media/硬链接/biliCollection/mine/BV1184y1a7ya-poster',
  escapedCommand: 'ln "/biliCollention/mine-default/BV1184y1a7ya-poster.jpg" "/media/硬链接/biliCollection/mine/BV1184y1a7ya-poster"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'ln: /media/硬链接/biliCollection/mine/BV1184y1a7ya-poster/BV1184y1a7ya-poster.jpg: Cross-device link',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.16.0

[24/04/07 21:59:10]  ERROR  任务执行出错，已终止

**Comment by likun7981** [comment]
`Cross-device link` 跨盘，麻烦多看下历史issue
