### ISSUE TITLE
本地使用gitbash可以运行，但是webui运行会报错；及本地缓存似乎有点小问题

### ISSUE THREAD

**Issue by 53nemu** [likun7981/hlink#184]
首先是webui的问题：
[24/05/23 08:59:45]  INFO  当前配置如下
[24/05/23 08:59:45]  INFO  包含规则: **/*.mp4,**/*.flv,**/*.f4v,**/*.webm,**/*.m4v,**/*.mov,**/*.cpk,**/*.dirac,**/*.3gp,**/*.3g2,**/*.rm,**/*.rmvb,**/*.wmv,**/*.avi,**/*.asf,**/*.mpg,**/*.mpeg,**/*.mpe,**/*.vob,**/*.mkv,**/*.ram,**/*.qt,**/*.fli,**/*.flc,**/*.mod,**/*.iso
[24/05/23 08:59:45]  INFO  排查规则: 无
[24/05/23 08:59:45]  INFO  缓存: 已关闭
[24/05/23 08:59:45]  INFO  保持原有目录结构: 是
[24/05/23 08:59:45]  INFO  为独立文件创建文件夹: 是
[24/05/23 08:59:45]  INFO  任务开始!
[24/05/23 08:59:45]  INFO  共计 1 个分析任务
[24/05/23 08:59:45]  INFO  执行分析任务: videos-origin > video
(node:19564) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: ls -iRFL F:\videos-origin
'ls' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
    at makeError (file:///C:/Users/q2799/AppData/Roaming/nvm/v14.21.3/node_modules/hlink/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///C:/Users/q2799/AppData/Roaming/nvm/v14.21.3/node_modules/hlink/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async lsirf (file:///C:/Users/q2799/AppData/Roaming/nvm/v14.21.3/node_modules/hlink/node_modules/@hlink/core/lib/core/lsirfl.js:8:22)
    at async parseLs (file:///C:/Users/q2799/AppData/Roaming/nvm/v14.21.3/node_modules/hlink/node_modules/@hlink/core/lib/core/parseLsirfl.js:7:17)
    at async analyse (file:///C:/Users/q2799/AppData/Roaming/nvm/v14.21.3/node_modules/hlink/node_modules/@hlink/core/lib/main/analyse.js:14:26)
    at async Promise.all (index 0)
    at async hlink (file:///C:/Users/q2799/AppData/Roaming/nvm/v14.21.3/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:27:6)
    at async main (file:///C:/Users/q2799/AppData/Roaming/nvm/v14.21.3/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5)
(Use `node --trace-warnings ...` to show where the warning was created)

(node:19564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19564) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

但是本地可以正常运行的

第二个问题是我在本地的运行似乎没有及时生成缓存，我确认我配置下已经把缓存打开，但是依旧会重复链接部分文件，请问我该怎么处理

**Comment by SNamiris** [comment]
为什么我在windows运行处理nas映射文件的时候全都是卡死

**Comment by Manuel-Zheng** [comment]
你好，你windows的本地路径怎么填写的

**Comment by up55** [comment]
> 你好，你windows的本地路径怎么填写的

需要用转义字符，简单来说就是所有```\```替换为```\\```
```
// 例如：
pathsMapping: {
        "D:\\lib\\downloads": "D:\\lib\\library"
    }
```
