### ISSUE TITLE
ERROR  未知错误, 请完整截图咨询

### ISSUE THREAD

**Issue by lxlalalala** [likun7981/hlink#191]
系统是群晖7.2.
本身是直接用命令行来使用hlink的，但是GUI开启后进去一次，再就进不去了，重装hlink，但是启动GUI，虽然提示SUCCEED，但还是进不去UI。
所以就装了docker版，但是因为我想映射的文件盒目标文件夹不在一个共享目录里，所以我在容器存储空间映射里加了点自己在其他docker里看到的一个做法，就是映射多个文件夹。
除了data，我还映射的另外俩，这俩都在一个存储空间上：
/musci：/pt/musci
/docker/xiaomusci/music：/pt/xiaomusic
hlink配置文件弄的是/pt/music': '/pt/xiaomusic
这样就出现了下面的报错。
这个是不是因为是能按照说明文档映射一个pt文件夹啊？
但是我这在一个文件夹里搞不定啊
也试了命令行版，GUI界面也进不去，直接在ssh里弄配置文件来运行也不成功。
所以这种情况应该咋操作啊？

[24/12/10 14:22:15]  INFO  当前配置如下
[24/12/10 14:22:15]  INFO  包含规则: 所有文件
[24/12/10 14:22:15]  INFO  排查规则: 无
[24/12/10 14:22:15]  INFO  缓存: 已打开
[24/12/10 14:22:15]  INFO  保持原有目录结构: 否
[24/12/10 14:22:15]  INFO  为独立文件创建文件夹: 是
[24/12/10 14:22:15]  INFO  任务开始!
[24/12/10 14:22:15]  INFO  共计 1 个分析任务
[24/12/10 14:22:15]  INFO  执行分析任务: music > xiaomusic
[24/12/10 14:22:15]  SUCCEED  分析任务执行完毕: music > xiaomusic
[24/12/10 14:22:15]  INFO  共计 2311 个文件
[24/12/10 14:22:15]  INFO  不满足配置的文件 0 个
[24/12/10 14:22:15]  INFO  已存在硬链的文件 0 个
[24/12/10 14:22:15]  INFO  缓存的创建记录 0 条
[24/12/10 14:22:15]  INFO  需要硬链的文件 2311 个
[24/12/10 14:22:15]  INFO  如果你看到这个消息，说明你的bash不支持格式化输入
[24/12/10 14:22:16]  ERROR  未知错误, 请完整截图咨询!
[24/12/10 14:22:16]  ERROR  Error: Command failed with exit code 1: ln /pt/music/Beyond/海阔天空.flac /pt/xiaomusic/Beyond
ln: /pt/xiaomusic/Beyond/海阔天空.flac: Cross-device link
file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: ln /pt/music/Beyond/海阔天空.flac /pt/xiaomusic/Beyond
ln: /pt/xiaomusic/Beyond/海阔天空.flac: Cross-device link
    at makeError (file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/local/lib/node_modules/hlink/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async link (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/link.js:21:9)
    at async callback (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:67:21)
    at async Promise.all (index 0)
    at async execAsyncByGroup (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/utils/execAsyncByGroup.js:7:9)
    at async hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:62:9)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5) {
  shortMessage: 'Command failed with exit code 1: ln /pt/music/Beyond/海阔天空.flac /pt/xiaomusic/Beyond',
  command: 'ln /pt/music/Beyond/海阔天空.flac /pt/xiaomusic/Beyond',
  escapedCommand: 'ln "/pt/music/Beyond/海阔天空.flac" "/pt/xiaomusic/Beyond"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'ln: /pt/xiaomusic/Beyond/海阔天空.flac: Cross-device link',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.16.0

[24/12/10 14:22:16]  ERROR  任务执行出错，已终止

**Comment by likun7981** [comment]
Cross-device link 看官方文档常见问题 这个关键字
