### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by klchen0112** [likun7981/hlink#25]
环境为unraid nodejs 版本为14.17.3
```
TypeError: Cannot read property 'join' of undefined
    at Object.parseConfig [as default] (/mnt/user/appdata/nodejs/node-v14.17.3-linux-x64/lib/node_modules/hlink/lib/config/parseConfig.js:26:40)
    at Object.<anonymous> (/mnt/user/appdata/nodejs/node-v14.17.3-linux-x64/lib/node_modules/hlink/lib/utils/parse.js:144:47)
    at step (/mnt/user/appdata/nodejs/node-v14.17.3-linux-x64/lib/node_modules/hlink/lib/utils/parse.js:52:23)
    at Object.next (/mnt/user/appdata/nodejs/node-v14.17.3-linux-x64/lib/node_modules/hlink/lib/utils/parse.js:33:53)
    at fulfilled (/mnt/user/appdata/nodejs/node-v14.17.3-linux-x64/lib/node_modules/hlink/lib/utils/parse.js:24:58)
```

```js
module.exports = {
  source: '',
  dst: '',
  icludeExtname: ['mp4', 'flv', 'f4v', 'webm',
    'm4v', 'mov', 'cpk', 'dirac',
    '3gp', '3g2', 'rm', 'rmvb',
    'wmv', 'avi', 'asf', 'mpg',
    'mpeg', 'mpe', 'vob', 'mkv',
    'ram', 'qt', 'fli', 'flc', 'mod', 'iso'],
  excludeExtname: [],
  maxFindLevel: 4,
  saveMode: 0
}
```

**Comment by likun7981** [comment]
`icludeExtname ` 拼写错误
