### ISSUE TITLE
群晖6.2.3无法运行

### ISSUE THREAD

**Issue by Cyberxxt** [likun7981/hlink#35]
ssh进去直接打的命令“hlink /volume2/movie/Malignant.2021.1080p /volume2/docker/emby/share”

[HLINK` ERROR]: Error: Command failed with exit code 1 (EPERM): ln /volume2/movie/Malignant.2021.1080p/Malignant.2021.1080p.HMAX.WEB-DL.DD5.1.x264-CMRG-clearlogo.png /volume2/docker/emby/share/Malignant.2021.1080p.HMAX.WEB-DL.DD5.1.x264-CMRG-clearlogo

    at makeError (/usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59:11)
    at Function.module.exports.sync (/usr/local/lib/node_modules/hlink/node_modules/execa/index.js:187:17)
    at /usr/local/lib/node_modules/hlink/lib/index.js:141:61
    at step (/usr/local/lib/node_modules/hlink/lib/index.js:52:23)
    at Object.next (/usr/local/lib/node_modules/hlink/lib/index.js:33:53)
    at /usr/local/lib/node_modules/hlink/lib/index.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/hlink/lib/index.js:23:12)
    at /usr/local/lib/node_modules/hlink/lib/index.js:80:65
    at Array.forEach (<anonymous>) {
  command: 'ln /volume2/movie/Malignant.2021.1080p/Malignant.2021.1080p.HMAX.WEB-DL.DD5.1.x264-CMRG-clearlogo.png /volume2/docker/emby/share/Malignant.2021.1080p.HMAX.WEB-DL.DD5.1.x264-CMRG-clearlogo',
  exitCode: 1,
  exitCodeName: 'EPERM',
  stdout: '',
  stderr: 'ln: failed to create hard link ‘/volume2/docker/emby/share/Malignant.2021.1080p.HMAX.WEB-DL.DD5.1.x264-CMRG-clearlogo/Malignant.2021.1080p.HMAX.WEB-DL.DD5.1.x264-CMRG-clearlogo.png’ => ‘/volume2/movie/Malignant.2021.1080p/Malignant.2021.1080p.HMAX.WEB-DL.DD5.1.x264-CMRG-clearlogo.png’: Invalid cross-device link',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined

**Comment by likun7981** [comment]
`Invalid cross-device link`  跨盘
