### ISSUE TITLE
unraid userscipt 自动运行出错

### ISSUE THREAD

**Issue by ourpurple** [likun7981/hlink#50]
Script location: /tmp/user.scripts/tmpScripts/auto hlink/script
Note that closing this window will abort the execution of this script
internal/process/esm_loader.js:74
internalBinding('errors').triggerUncaughtException(
^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. Received protocol 'node:'
at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:782:11)
at Loader.resolve (internal/modules/esm/loader.js:85:40)
at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
at ModuleWrap. (internal/modules/esm/module_job.js:51:40)
at link (internal/modules/esm/module_job.js:50:36) {
code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}

/mnt/user/domains/node-v16.14.2-linux-x64/bin/hlink -e=jpg,png,bmp /mnt/user/download_media/download/Disc/ /mnt/user/download_media/media/Movies/Disc/

在shell窗口运行没有问题，在userscript中自动运行提示最上面的错误。

**Comment by likun7981** [comment]
已恢复，这是unraid的node版本不正确
