### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by jsdfhasuh** [likun7981/hlink#82]
/ # hlink -g
Error: 必须指定配置文件
    at warning (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/utils/index.js:50:15)
    at Object.get (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/config/get.js:5:5)
    at hlink (file:///usr/local/lib/node_modules/hlink/lib/bins/hlink.js:36:26)
    at file:///usr/local/lib/node_modules/hlink/lib/cli.js:66:9
/ #

**Comment by likun7981** [comment]
看下2.0的文档或者`hlink --help`，目前已更新为 `hlink g /path/to/configSaveDir`
