### ISSUE TITLE
"未知错误, 请完整截图咨询!"

### ISSUE THREAD

**Issue by Volcano2333** [likun7981/hlink#87]
请大佬帮忙看看是哪出错了

平台：TrueNAS-SCALE-22.02.2.1
通过Docker Image安装

```
任务列表

test
配置: test
硬链
配置列表
test
test
MIT Licensed | Copyright © 2019-present likun & hlink Contributors
任务 test 执行出错
[22/08/07 13:24:22]  INFO  当前配置如下
[22/08/07 13:24:22]  INFO  包含规则: **/*.mp4,**/*.flv,**/*.f4v,**/*.webm,**/*.m4v,**/*.mov,**/*.cpk,**/*.dirac,**/*.3gp,**/*.3g2,**/*.rm,**/*.rmvb,**/*.wmv,**/*.avi,**/*.asf,**/*.mpg,**/*.mpeg,**/*.mpe,**/*.vob,**/*.mkv,**/*.ram,**/*.qt,**/*.fli,**/*.flc,**/*.mod,**/*.iso
[22/08/07 13:24:22]  INFO  排查规则: 无
[22/08/07 13:24:22]  INFO  缓存: 已关闭
[22/08/07 13:24:22]  INFO  保持原有目录结构: 是
[22/08/07 13:24:22]  INFO  为独立文件创建文件夹: 否
[22/08/07 13:24:22]  INFO  任务开始!
[22/08/07 13:24:22]  INFO  共计 1 个分析任务
[22/08/07 13:24:22]  INFO  执行分析任务: bt > hlinkFiles
[22/08/07 13:24:22]  SUCCEED  分析任务执行完毕: bt > hlinkFiles
[22/08/07 13:24:22]  INFO  共计 1 个文件
[22/08/07 13:24:22]  INFO  不满足配置的文件 0 个
[22/08/07 13:24:22]  INFO  已存在硬链的文件 0 个
[22/08/07 13:24:22]  INFO  需要硬链的文件 1 个
[22/08/07 13:24:22]  INFO  如果你看到这个消息，说明你的bash不支持格式化输入
[22/08/07 13:24:22]  ERROR  未知错误, 请完整截图咨询!
[22/08/07 13:24:22]  ERROR  Error: Command failed with exit code 1: ln /btDownloads/bt/[Moretsu Uchuu Kaizoku][26][576].mp4 /btDownloads/hlinkFiles
ln: /btDownloads/hlinkFiles/[Moretsu Uchuu Kaizoku][26][576].mp4: Cross-device link
file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: ln /btDownloads/bt/[Moretsu Uchuu Kaizoku][26][576].mp4 /btDownloads/hlinkFiles
ln: /btDownloads/hlinkFiles/[Moretsu Uchuu Kaizoku][26][576].mp4: Cross-device link
    at makeError (file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/local/lib/node_modules/hlink/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async link (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/link.js:21:9)
    at async callback (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:67:21)
    at async Promise.all (index 0)
    at async execAsyncByGroup (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/utils/execAsyncByGroup.js:7:9)
    at async hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:62:9)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5) {
  shortMessage: 'Command failed with exit code 1: ln /btDownloads/bt/[Moretsu Uchuu Kaizoku][26][576].mp4 /btDownloads/hlinkFiles',
  command: 'ln /btDownloads/bt/[Moretsu Uchuu Kaizoku][26][576].mp4 /btDownloads/hlinkFiles',
  escapedCommand: 'ln "/btDownloads/bt/[Moretsu Uchuu Kaizoku][26][576].mp4" "/btDownloads/hlinkFiles"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'ln: /btDownloads/hlinkFiles/[Moretsu Uchuu Kaizoku][26][576].mp4: Cross-device link',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

[22/08/07 13:24:22]  ERROR  任务执行出错，已终止
```

![image](https://user-images.githubusercontent.com/50535968/183293137-c87a8316-d065-4576-8683-ccba87ea21ca.png)

**Comment by likun7981** [comment]
Cross-device link 跨盘或者跨共享文件夹
