### ISSUE TITLE
我的一个子文件夹内存在大量文件，接近20万个，硬链接失败，错误信息附上

### ISSUE THREAD

**Issue by shine437** [likun7981/hlink#95]
[22/09/22 20:40:03]  INFO  当前配置如下
[22/09/22 20:40:03]  INFO  包含规则: **/*.jpg,**/*.jpeg,**/*.png
[22/09/22 20:40:03]  INFO  排查规则: 无
[22/09/22 20:40:03]  INFO  缓存: 已关闭
[22/09/22 20:40:03]  INFO  保持原有目录结构: 是
[22/09/22 20:40:03]  INFO  为独立文件创建文件夹: 否
[22/09/22 20:40:03]  INFO  任务开始!
[22/09/22 20:40:03]  INFO  共计 1 个分析任务
[22/09/22 20:40:03]  INFO  执行分析任务: Hsources > Target
[22/09/22 20:40:10]  SUCCEED  分析任务执行完毕: Hsources > Target
file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:38
        waitLinkFiles.push(...item.waitLinkFiles);
                      ^

RangeError: Maximum call stack size exceeded
    at file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:38:23
    at Array.forEach ()
    at hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:37:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5)

[22/09/22 20:40:10]  ERROR  任务执行出错，已终止

**Comment by likun7981** [comment]
建议拆一下，目测是文件太多造成的内存泄漏，目前没有测试过这么多

**Comment by likun7981** [comment]
拆分后如果没什么问题，这个问题就先关闭了
