### ISSUE TITLE
ERROR  Error: Command failed with exit code 1:

### ISSUE THREAD

**Issue by laoma2016** [likun7981/hlink#98]
22/10/02 06:14:02]  INFO  当前配置如下
[22/10/02 06:14:02]  INFO  包含规则: **/*.mp4,**/*.flv,**/*.f4v,**/*.webm,**/*.m4v,**/*.mov,**/*.cpk,**/*.dirac,**/*.3gp,**/*.3g2,**/*.rm,**/*.rmvb,**/*.wmv,**/*.avi,**/*.asf,**/*.mpg,**/*.mpeg,**/*.mpe,**/*.vob,**/*.mkv,**/*.ram,**/*.qt,**/*.fli,**/*.flc,**/*.mod,**/*.iso
[22/10/02 06:14:02]  INFO  排查规则: 无
[22/10/02 06:14:02]  INFO  缓存: 已关闭
[22/10/02 06:14:02]  INFO  保持原有目录结构: 否
[22/10/02 06:14:02]  INFO  为独立文件创建文件夹: 否
[22/10/02 06:14:02]  INFO  任务开始!
[22/10/02 06:14:02]  INFO  共计 1 个分析任务
[22/10/02 06:14:02]  INFO  执行分析任务: movie > hlink/data
[22/10/02 06:14:08]  SUCCEED  分析任务执行完毕: movie > hlink/data
[22/10/02 06:14:08]  INFO  共计 17278 个文件
[22/10/02 06:14:08]  INFO  不满足配置的文件 14380 个
[22/10/02 06:14:08]  INFO  已存在硬链的文件 0 个
[22/10/02 06:14:08]  INFO  需要硬链的文件 2898 个
[22/10/02 06:14:08]  INFO  如果你看到这个消息，说明你的bash不支持格式化输入
[22/10/02 06:14:09]  ERROR  未知错误, 请完整截图咨询!
[22/10/02 06:14:09]  ERROR  Error: Command failed with exit code 1: ln /movie/[侏罗纪世界3]Jurassic.World.Dominion.2022.Extended.Cut.Blu-ray.1080p.x264.DTS-HD.MA.7.1-BtsHD.mkv /hlink/data
ln: /hlink/data/[侏罗纪世界3]Jurassic.World.Dominion.2022.Extended.Cut.Blu-ray.1080p.x264.DTS-HD.MA.7.1-BtsHD.mkv: Cross-device link
file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: ln /movie/[侏罗纪世界3]Jurassic.World.Dominion.2022.Extended.Cut.Blu-ray.1080p.x264.DTS-HD.MA.7.1-BtsHD.mkv /hlink/data
ln: /hlink/data/[侏罗纪世界3]Jurassic.World.Dominion.2022.Extended.Cut.Blu-ray.1080p.x264.DTS-HD.MA.7.1-BtsHD.mkv: Cross-device link
    at makeError (file:///usr/local/lib/node_modules/hlink/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/local/lib/node_modules/hlink/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async link (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/link.js:21:9)
    at async callback (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:67:21)
    at async Promise.all (index 3)
    at async execAsyncByGroup (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/utils/execAsyncByGroup.js:7:9)
    at async hlink (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/hlink.js:62:9)
    at async main (file:///usr/local/lib/node_modules/hlink/node_modules/@hlink/core/lib/main/index.js:4:5) {
  shortMessage: 'Command failed with exit code 1: ln /movie/[侏罗纪世界3]Jurassic.World.Dominion.2022.Extended.Cut.Blu-ray.1080p.x264.DTS-HD.MA.7.1-BtsHD.mkv /hlink/data',
  command: 'ln /movie/[侏罗纪世界3]Jurassic.World.Dominion.2022.Extended.Cut.Blu-ray.1080p.x264.DTS-HD.MA.7.1-BtsHD.mkv /hlink/data',
  escapedCommand: 'ln "/movie/[侏罗纪世界3]Jurassic.World.Dominion.2022.Extended.Cut.Blu-ray.1080p.x264.DTS-HD.MA.7.1-BtsHD.mkv" "/hlink/data"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'ln: /hlink/data/[侏罗纪世界3]Jurassic.World.Dominion.2022.Extended.Cut.Blu-ray.1080p.x264.DTS-HD.MA.7.1-BtsHD.mkv: Cross-device link',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

[22/10/02 06:14:09]  ERROR  任务执行出错，已终止

是因为PT的文件夹名太长的原因吗？帮忙看看，谢谢！

**Comment by laoma2016** [comment]
跨盘的原因
